import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components";
import { Layout } from "@/components";
import { StateContext } from '../context/StateContext'
import { Toaster } from 'react-hot-toast';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ 
  children, 
}:{
  children: React.ReactNode
}){

  return (
    <html>
      <body
        className={`${geistSans.variable} ${geistMono.variable}`}
      >
          <StateContext>
            <Layout>

            {/* <Navba></Navba> */}
          
          <Toaster />
          {children}
          </Layout>
          </StateContext>
      </body>
    </html>
    
  )
}
